name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image for FRONT
        run: sudo docker pull denstan/front:latest
      - name: Delete old container
        run: sudo docker rm -f front-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --name front-container denstan/front

      - name: Delete old images
        run: docker images | grep '<none>' | awk '{ print $3 }' | xargs docker rmi